title: FoodEstetic - Блог о красивой и здоровой еде
name: "Food Esthetic"
description: Красивая и здоровая пища - красивые и здоровые тело и дух
themecolor: '#F1B501'
imagehome: img/FoodEstetic.jpg
url: "https://foodestetic.github.io"
baseurl: "/"
plugins: [jekyll-paginate-v2]
category_dir: blog
pagination:
  enabled: true
  per_page: 24
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
soc:
  <li><a href="#"><i class="fab fa-xs fa-facebook fa-xs"></i></a></li>
  <li><a href="#"><i class="fab fa-xs fa-vk fa-xs"></i></a></li>
  <li><a href="#"><i class="fab fa-xs fa-youtube fa-xs"></i></a></li>
  <li><a href="#"><i class="fab fa-xs fa-instagram fa-xs"></i></a></li>
copyright: Копирование контента и размещение на других сайтах запрещено.
exclude: ['node_modules', 'jekyll-paginate-v2', 'gulpfile.js', 'package.json', 'package-lock.json', 'js/common.js', 'npm-debug.log', '**/Thumbs.db', 'libs', 'sass', '**/*.DS_Store']